### PR TITLE
feat: add rules page

### PR DESCRIPTION
**Pull request by Maianki**
## Added rules page
Rules page screenshot

## Live Link
https://rules-page.netlify.app/

### CODE REVIEW

**Review by VLeads — APPROVED** [review]
Looking good. Go ahead !

**Review by sainath7878 — APPROVED** [review]
Looks good to merge

**Comment by Maianki** [comment]
> Looking good. Go ahead !

Thanks for reviewing.

**Comment by Maianki** [comment]
> Looks good to merge

Thanks for reviewing.

**Pull request merged**
