### PR TITLE
Home page

### PR DESCRIPTION
**Pull request by Maianki**
## Added landing page 

Screenshot (597)

## Live Link
https://quiz-homepage.netlify.app/

### Thanks for reviewing my PR

### CODE REVIEW

**Review by sainath7878 — APPROVED** [review]
Looks good to merge

**Review by BalajiHarinath — APPROVED** [review]
Looks good to merge.

**Review by VLeads — APPROVED** [review]
You have used good practices from html to CSS. You can merge now !!

**Comment by Maianki** [comment]
Thanks for reviewing.

**Pull request merged**
